config/routes.rb
Mysize::Application.routes.draw do
  # active admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # api server
  mount MySize::API => '/api'
  
  # web widget
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get :signin, to: 'users#login'
  get :logout, to: 'sessions#destroy'
  get :reset_password, to: 'password_resets#new'
  post :reset_password, to: 'password_resets#create'
  get :set_new_password, to: 'password_resets#edit'
  post :set_new_password, to: 'password_resets#update'

  resources :users do 
    get :successful_login
  end
  resource :web_widget do
  	get :main
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.active.find_by(username: params[:email])
    return redirect_to :back, alert: 'Invalid email address.' if user.blank? || user.auth_type != User::AUTH_TYPE_PASSWORD

    # create a unique password reset token
    begin 
      user.reset_password_token = SecureRandom.hex(21)
      user.reset_password_sent_at = Time.now
    end while User.find_by(reset_password_token: user.reset_password_token)

    return redirect_to :back, alert: 'Could not create password reset token, please try again later.' unless user.save
    AuthMailer.reset_password(user).deliver 
  end
  
  def edit
    @user = User.active.find_by(username: params[:email], reset_password_token: params[:token])
  end
  
  def update
    user = User.active.find_by(username: params[:user][:email], reset_password_token: params[:user][:token])
    return redirect_to reset_password_path, alert: 'Invalid password reset token. Please try again.' if user.blank? || user.reset_password_sent_at < 1.hour.ago
    return redirect_to :back, alert: 'Could not set new password, please try again later.' unless user.update_attributes(password: params[:user][:password], reset_password_token: nil, reset_password_sent_at: nil)
  end  
end

app/views/password_resets/create.html.erb
<div class="container">
	<div class="well col-md-12 col-xs-12">
		<h1>Password reset mail sent!</h1>
	</div>
</div>

app/views/password_resets/edit.html.erb
<div class="container">
  <div class="well col-md-12 col-xs-12">
      <h1>Set new password</h1>
      <% unless flash[:alert].blank? %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>

      <%= form_for @user, url: set_new_password_path, method: :post do |f| %>
        <%= f.hidden_field :email, value: @user.username %>
        <%= f.hidden_field :token, value: @user.reset_password_token %>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'password (again)' %>
        </div>

        <%= submit_tag 'reset password', class: 'btn btn-default' %>
      <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="container">
	<div class="well col-md-12 col-xs-12">
		<h1>Reset Password</h1>
	    <% unless flash[:alert].blank? %>
	    	<div class="alert alert-danger"><%= flash[:alert] %></div>
	    <% end %>

		<%= form_tag reset_password_path, :method => :post do %>
  			<div class="form-group">
				<%= label_tag :email %>
				<%= text_field_tag :email, params[:email], class: 'form-control', placeholder: 'enter your email address' %>
  			</div>

			<%= submit_tag 'submit', class: 'btn btn-default' %>
		<% end %>		
	</div>
</div>

app/views/password_resets/update.html.erb
<div class="container">
	<div class="well col-md-12 col-xs-12">
		<h1>Password changed!</h1>
	</div>
</div>