config/routes.rb
Mysize::Application.routes.draw do
  # active admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # api server
  mount MySize::API => '/api'
  
  # web widget
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get :signin, to: 'users#login'
  get :logout, to: 'sessions#destroy'
  get :reset_password, to: 'password_resets#new'
  post :reset_password, to: 'password_resets#create'
  get :set_new_password, to: 'password_resets#edit'
  post :set_new_password, to: 'password_resets#update'

  resources :users do 
    get :successful_login
  end
  resource :web_widget do
  	get :main
  end
end

app/controllers/web_widgets_controller.rb
class WebWidgetsController < ApplicationController
	require 'uri' #decode url
	before_filter :current_user

	def main
		puts "A"
		puts @current_user 
		cookies[:original_url] = params[:url]
		cookies[:business_id] = params[:business_id]
		cookies.permanent[:product_id] = params[:product_id]
		if @current_user
			puts "here!!!!!!!!!!"
			# suggest a size for the given product; get business and product
			business = Business.active.find_by(token: params[:business_id])

			unless business.blank?
				product = business.products.find_by(serial: params[:product_id])
				puts "here!!!!!!!!!!"
				unless product.blank?
					# query the business's size chart
					@result = business.sizes.where('category_id = :category and ((min_bust <= :bust and max_bust >= :bust) or (min_waist <= :waist and max_waist >= :waist))', category: product.category_id, bust: @current_user.bust, waist: @current_user.waist).first
				end
			end
		end
	end
end

app/views/web_widgets/main.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-md-12">
			<% if @current_user %>
				<div class="settings_container">
					<%= link_to edit_user_path(@current_user.id) do %>
						<%= image_tag "mysize_settings.png", :class => "settings_image" %>
					<% end %>
				</div>
		<!-- 	<div class="title_container">
					<%= image_tag("mysize_logo_1.png") %>
				</div>	-->
				<div class="logged_title_container">
					<h1>HI <%= @current_user.first_name.upcase %>!</h1>
				</div>
				<% unless @result.blank? %>
					<div class="nice_container">
						<section>Nice to see you again.<br>Your suggested size for this<br>product is:</section>
						<h2><%= @result.name %></h2>
					</div>
				<% else %>
					<div class="nice_container">
						<section class="no_size_margin_bottom">Unfortunatley no size<br>could be matched for you<br>in this store.</section>
					</div>
				<% end %>
				<div class="button_padding">
					<%= link_to logout_path do %>
						<div class= 'azure_button logout_button'>
							not <%= @current_user.first_name %>? Log out
						</div>
					<%end%>
				</div>
			<% else %>
				<div class="title_container">
					<h1>SIGN IN WITH</h1>
					<%= image_tag("mysize_logo_1.png") %>
				</div>
	    		<% unless flash[:alert].blank? %>
	    			<div class="alert alert-danger"><%= flash[:alert] %></div>
	    		<% end %>

	    		<div >
					<%= form_tag login_path, method: :post do %>
						<input name="<%= request_forgery_protection_token.to_s %>" type="hidden" value="<%= form_authenticity_token %>" />
						<div class="textbox_container">
							<%= text_field_tag :username, params[:username], class: 'mysize_textbox bottom_border_textbox', placeholder: 'Username' %>
							<%= password_field_tag :password, params[:password], class: 'mysize_textbox', placeholder: 'Password' %>
			  			</div>
			  				<%= button_tag( class: 'azure_button', type: :submit) do %>
			  				Login
			                  <%= image_tag("login_arrow.png")%>
			                <% end %>
					<% end %>
				</div>
				<div >
					<h2 class="forgot_container">Forgot password?</h2>
					<%= link_to new_user_path , class: 'not_a_member_container' do %>
						<h2>Not a member?</h2>
					<%end%>
				</div>
			<% end %>
		</div>
	</div>
</div>